import { PATHS } from "./consts";

export const labels = {
    BASIC_INFO: 'Basic info',
    FEATURES: 'Features',
    LOCATION: 'Location',
    PHOTO: 'Photo',
    THERE_WAS_AN_UNEXPECTED_ERROR: 'There was an unexpected error',
    BACK: 'Back',
    NEXT: 'Next',
    CREATE_OFFER: 'Create offer',
    ASK_FOR_PRICE: 'Ask for price',
    CONTACT_SELLER: 'Contact seller',
    DETAILS: 'Details',
    MANUFACTURER: 'Manufacturer',
    MODEL: 'Model',
    PRODUCTION_YEAR: 'Production year',
    PRICE: 'Price',
    MILEAGE: 'Mileage',
    HORSEPOWER: 'Horsepower',
    FUEL_TYPE: 'Fuel type',
    FUEL_TYPES: {
        PETROL: 'Petrol',
        DIESEL: 'Diesel',
        LPG: 'LPG',
        HYBRID: 'Hybrid',
        ELECTRIC: 'Electric'
    },
    AUTH_ERRORS: {
        USER_NOT_FOUND: "User was not found",
        WRONG_PASSWORD: "Wrong password",
        SIGN_IN_CANCELLED: "Sign in was cancelled",
        EMAIL_IN_USE: "Email already in use",
        WEAK_PASSWORD: "Password is too weak"
    },
    EMAIL: 'Email address',
    PASSWORD: 'Password',
    REGISTER_HERE: 'Register here',
    LOG_IN_INSTEAD: 'Log in instead',
    AUTH_HINT_TO_LOGIN: 'Already have an account?',
    AUTH_HINT_TO_REGISTER: 'Don\'t have an account?',
    LOG_IN: 'Log In',
    LOG_IN_WITH_GOOGLE: 'Log In with Google',
    REGISTER: 'Register',
    SIGN_IN: 'Sign in',
    SIGN_OUT: 'Sign out',
    ADD_OFFER: 'Add offer',
    SELECT_FUEL_TYPE: 'Select fuel type',
    FEATURES_FORM_EMPTY_HINT: 'Add features in form below! (heated seats, rear view camera etc.)',
    ADD: 'Add',
    REMOVE: 'Remove',
    UNABLE_TO_FIND_LOCATION_ERROR: 'Couldn\'t find the location',
    GET_CURRENT_LOCATION: 'Get my current location',
    LOCATION_FORM_EMPTY_HINT: 'Put in your location above!',
    THIS_PAGE_DOES_NOT_EXIST: 'This page does not exist',
    PATHS: {
        [PATHS.SIGN_IN]: 'Sign in',
        [PATHS.OFFER_CREATE]: 'Create an offer',
        [PATHS.OFFER_DETAILS]: 'Offer details',
        [PATHS.CHATS]: 'Chats'
    }
}